# Java Maven CircleCI 2.0 configuration file.
# そもそもそんなに遅くないのでキャッシュは取らないで実行します。
 version: 2
 jobs:
   build:
     working_directory: ~/repo

     docker:
       - image: circleci/openjdk:8u242-jdk

     environment:
       # Customize the JVM maximum heap limit.
       MAVEN_OPTS: -Xmx3200m

     steps:
       - checkout
       - run: mvn clean
       - run: mvn package
       - store_test_results:
           path: target/surefire-reports
       - store_artifacts:
           path: target/CPhone-1.3.5-SNAPSHOT.jar
